config/routes.rb
Rails.application.routes.draw do

  resources :users, except: :index
  resources :listings, only: [:index, :new, :create, :update, :show, :destroy]
  resources :bookings, only: [:index, :new, :create, :update, :show, :destroy]

  get '/', to: 'application#welcome_1', as: 'welcome_1'

  get '/login', to: 'sessions#new', as: 'new_session'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get '/about', to: "application#about", as: 'about'

  get '/lister_show/:id', to: 'listings#lister_show', as: 'lister_show'

  get '/users/:id/new_listing', to: "listings#new", as: "create_listing"
  get '/users/:id/lister_listing', to: "listings#lister_listing", as: "lister_listing"
  get '/users/:id/edit_listing', to: "listings#edit", as: "edit_listing"

  get '/users/:start_date/:id/new_booking', to: "bookings#new", as: "create_booking"
  get '/users/:id/edit_booking', to: "bookings#edit", as: "edit_booking"

end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :bookings

  validates :location, presence: true

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authorized, only: [:new, :create]

  def index
    @listings = Listing.all

    @images  = ["1.jpeg", "2.jpeg", "3.jpeg", "4.jpeg", "5.jpeg", "6.jpeg", "8.jpeg", "9.jpeg", "10.jpeg", "11.jpeg", "12.jpeg", "13.jpeg", "14.jpeg", "16.jpeg", "17.jpeg", "19.jpeg", "21.jpeg", "22.jpeg", "23.jpeg", "24.jpeg", "25.jpeg", "26.jpeg", "27.jpg", "28.jpg", "29.jpg", "30.jpg", "31.jpg", "32.jpeg"]
    @random_no = rand(29)
    @random_image = @images[@random_no]
  end

  def show
    if session[:user_id]
      @lister = User.find(session[:user_id])
    end

    @images  = ["1.jpeg", "2.jpeg", "3.jpeg", "4.jpeg", "5.jpeg", "6.jpeg", "8.jpeg", "9.jpeg", "10.jpeg", "11.jpeg", "12.jpeg", "13.jpeg", "14.jpeg", "16.jpeg", "17.jpeg", "19.jpeg", "21.jpeg", "22.jpeg", "23.jpeg", "24.jpeg", "25.jpeg", "26.jpeg", "27.jpg", "28.jpg", "29.jpg", "30.jpg", "31.jpg", "32.jpeg"]
    @random_no = rand(29)
    @random_image = @images[@random_no]
  end

  def lister_show
    @lister = User.find(params[:id])
    @images  = ["ppl-1.jpeg", "ppl-2.jpeg", "ppl-3.jpeg", "ppl-4.jpeg", "ppl-5.jpeg", "ppl-6.jpeg", "ppl-7.jpeg", "ppl-8.jpeg", "ppl-9.jpeg", "ppl-10.jpeg", "ppl-11.jpeg", "ppl-13.jpeg", "ppl-14.jpeg", "ppl-15.jpeg", "ppl-16.jpeg", "ppl-17.jpeg", "ppl-18.jpeg", "ppl-19.jpeg", "ppl-20.jpeg", "ppl-21.jpeg", "ppl-22.jpeg", "ppl-24.jpeg", "ppl-25.jpeg", "ppl-26.jpeg"]
    @random_no = rand(24)
    @random_image = @images[@random_no]
  end

  def new
    @listing = Listing.new
    @user = User.find(session[:user_id])
    flash[:error] = nil
    @images  = ["1.jpeg", "2.jpeg", "3.jpeg", "4.jpeg", "5.jpeg", "6.jpeg", "8.jpeg", "9.jpeg", "10.jpeg", "11.jpeg", "12.jpeg", "13.jpeg", "14.jpeg", "16.jpeg", "17.jpeg", "19.jpeg", "21.jpeg", "22.jpeg", "23.jpeg", "24.jpeg", "25.jpeg", "26.jpeg", "27.jpg", "28.jpg", "29.jpg", "30.jpg", "31.jpg", "32.jpeg"]
    @random_no = rand(29)
    @random_image = @images[@random_no]
  end

  def create
    @listing = Listing.create(listing_params)
    if @listing.valid?
      session[:listing_id] = @listing.id
      redirect_to listing_path(@listing)
    else
      flash[:error] = @listing.errors.full_messages
      @listing = Listing.new
      @user = User.find(session[:user_id])
      render :new
    end
  end

  def edit
    flash[:error] = nil
    @lister = User.find(session[:user_id])
  end

  def update
    @listing.update(listing_params)
    if @listing.valid?
      redirect_to listing_path(@listing)
    else
      flash[:error] = @listing.errors.full_messages
      render :edit
    end
  end

  def destroy
    @listing.bookings.destroy
    @listing.destroy
    redirect_to user_path(@listing.user)
  end

  private

  def set_listing
    @listing = Listing.find(params[:id])
  end

  def listing_params
    params.require(:listing).permit(:user_id, :location, :img_url)
  end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/edit.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
  	<meta charset="UTF-8">
  	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
  	<meta name="viewport" content="width=device-width, initial-scale=1">
  	<%= stylesheet_link_tag "listings" %>
  	<title>New Listing</title>
  </head>
  <body>
    <% if flash[:error] %>
      <% flash[:error].each do |error| %>
        <li style="color:red"><%= error %></li>
      <% end %>
    <% end %>
      <header>
        <!--Navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top scrolling-navbar" style="position:absolute">
          <div class="container">
            <a class="logo navbar-brand" href="<%= welcome_1_path %>"><img src="/images/BestBookingTransparent.jpg" style="max-height: 50px;"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-7" aria-controls="navbarSupportedContent-7" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent-7">
              <ul class="navbar-nav mr-auto">
                <% if !session[:user_id] %>
                <li class="nav-item active">
                  <a class="nav-link-1" <%= link_to "Listings", listings_path %></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link-1" <%= link_to "Create Profile", new_user_path, method: :get %></a>
                </li>
                <% else %>
                <li class="nav-item">
                  <a class="nav-link-1" <%= link_to "View Profile", user_path(session[:user_id]), method: :get %></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link-1" <%= link_to "Listings", listings_path %></a>
                </li>
                <% end %>
              </ul>
              <form class="form-inline">
                <!-- <div class="md-form my-0">
                  <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                </div> -->
                <!-- <li class="nav-item"> -->
                  <a class="nav-link text-align-right blue" <%= link_to "Sign Out", logout_path, method: :delete %></a>
                <!-- </li> -->
              </form>
            </div>
          </div>
        </nav>
        <!-- Navbar -->

        <!-- Full Page Intro -->
        <div class="view" style="background-image: url('https://www.homebeautiful.com.au/cdnstorage/cache/2/8/b/3/1/2/x28b312de6dd7e408e11b484b0878c2977b0bc834.jpg.pagespeed.ic.KqScWjinVp.jpg'); background-repeat: no-repeat; background-size: cover; background-position: center center; opacity: 0.90;">
          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-light align-items-center">
            <!-- Content -->
            <div class="container">
              <!--Grid row-->
              <div class="row">
                <!--Grid column-->
                <div class="col-md-12 mb-4 white-text text-center">
                  <br>
                  <br>
                  <h1 style="color:rgb(131, 37, 38)" class="h1-reponsive white-text text-uppercase font-weight-bold mb-0 pt-md-5 pt-5 wow fadeInDown" data-wow-delay="0.3s"><strong>Edit Listing</strong></h1><br>
                  <!-- <hr class="hr-light my-4 wow fadeInDown" data-wow-delay="0.4s"> -->
                </div>
                <br>
                <br>
                <div class="card" style="border-radius:20px; width: 18rem; background-color:transparent; margin-left:37.5%; background-color: rgba(255, 255, 255, 0.65);">
                  <div class="card-body col text-center">
                    <%= form_for @listing do |f| %>
                      <%= f.hidden_field :user_id, value: @listing.user.id %>
                      <strong><%= f.label :location %></strong><br>
                      <%= f.text_field :location %><br><br>

                      <strong><%= f.label :img_url %></strong><br>
                      <%= f.text_field :img_url %><br><br>

                      <%= f.submit class: "btn btn-dark" %><br><br>
                    <% end %>
                    <div class="btn btn-outline-dark" style="border-radius: 8px;"><%= button_to "Delete Listing", listing_path(@listing), method: :delete, data: {confirm: "Are you sure you want to delete your listing?"} %></div>
                  </div>
                </div>
              </div>
              <!--Grid row-->

            </div>
            <!-- Content -->
          </div>
          <!-- Mask & flexbox options-->
        </div>
        <!-- Full Page Intro -->
      </header>
      <!-- Main navigation -->
      <!--Main Layout-->
      <main>
        <!-- <div class="container">
          <!--Grid row-->
          <!-- <div class="row py-5"> -->
            <!--Grid column-->
            <!-- <div class="col-md-12 text-center"> -->
              <!-- <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
              <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
              <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p> -->
            <!-- </div> -->
            <!--Grid column-->
          <!-- </div> -->
          <!--Grid row-->
        <!-- </div> -->
      </main>
      <!--Main Layout-->


      <footer class="text-center">
          <h4>BestBooking!</h4>
          <p>All Rights Reserved &trade;</p>
      </footer>

    </body>
</html>

app/views/listings/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag "listings" %>
    <title>Listings</title>
  </head>

  <body style="background-image: url('https://img1.southernliving.timeinc.net/sites/default/files/styles/4_3_horizontal_inbody_900x506/public/image/2016/04/main/white-kitchen-open-shelving-2464001-0003_2.jpg?itok=sTu0Rrv-'); background-repeat: no-repeat; background-attachment: fixed; background-position: center; background-size: cover;">
  <!-- nav -->
  <nav class="navbar navbar-expand-md fixed-top position: absolute; z-index: 5;">
      <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
          <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                  <a class="logo navbar-brand" href="<%= welcome_1_path %>"><img src="/images/BestBookingTransparent.jpg" style="max-height: 50px;"></a>
              </li>
              <% if !session[:user_id] %>
              <li class="nav-item">
                  <a class="nav-link blue" <%= link_to "Create Profile", new_user_path, method: :get %></a>
              </li>
              <% else %>
              <li class="nav-item">
                  <a class="nav-link blue" <%= link_to "View Profile", user_path(session[:user_id]), method: :get %></a>
              </li>
              <li class="nav-item">
                  <a class="nav-link blue" <%= link_to "Create a Listing", new_listing_path %></a>
              </li>
              <% end %>
          </ul>
      </div>
      <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
          <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                  <a class="nav-link text-align-right blue" <%= link_to "Sign Out", logout_path, method: :delete %></a>
              </li>
          </ul>
      </div>
  </nav>
  <!-- end-nav -->
  <!-- title -->
  <br>
  <br>
  <div class="container text-center" >
    <h1 >LISTINGS</h1>
    <br><h5 style="margin-bottom: 20px;">Where would you like to stay?</h5>
  </div>
  <!-- end-title -->
  <!-- main -->
  <div id="list-container" class="container-fluid text-center">
    <div id="list-row" class="row content">
      <div class="col-3">
      </div>
    <div class="justify-content-center list-holder">
      <div class="listing-list">
        <% @listings.each do |l| %>
          <p  id="list-index"><%= link_to l.location, listing_path(l) %></p>
        <% end %>
      </div>
    </div>
      <div class="col-3">
      </div>
    </div>
  </div>
  <!-- end main -->


  <!-- footer -->
  <div id="footer" class="container-fluid text-center">
      <h4>BestBooking!</h4>
      <p>All Rights Reserved &trade;</p>
  </div>
  <!-- end footer -->
  </body>
</html>

app/views/listings/lister_show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
  	<meta charset="UTF-8">
  	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
  	<meta name="viewport" content="width=device-width, initial-scale=1">
  	<%= stylesheet_link_tag "listings" %>
  	<title>Listing Show Page</title>
  </head>
  <body>
    <% if flash[:error] %>
      <% flash[:error].each do |error| %>
        <li style="color:red"><%= error %></li>
      <% end %>
    <% end %>
      <header>
        <!--Navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top scrolling-navbar" style="position:absolute">
          <div class="container">
            <a class="logo navbar-brand" href="<%= welcome_1_path %>"><img src="/images/BestBookingTransparent.jpg" style="max-height: 50px;"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-7" aria-controls="navbarSupportedContent-7" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent-7">
              <ul class="navbar-nav mr-auto">
                <% if !session[:user_id] %>
                <li class="nav-item-">
                  <a class="nav-link-1" <%= link_to "Login", new_session_path, method: :get %></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link-1" <%= link_to "Create Profile", new_user_path, method: :get %></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link-1" <%= link_to "All Listings", listings_path %></a>
                </li>
                <% else %>
                <li class="nav-item">
                  <a class="nav-link-1" <%= link_to "View Profile", user_path(session[:user_id]), method: :get %></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link-1" <%= link_to "All Listings", listings_path %></a>
                </li>
                <% if @lister == session[:user_id] %>
                  <li class="nav-item">
                    <a class="nav-link-1" <%= link_to "Edit Listing", edit_listing_path(@listing) %></a>
                  </li>
                <% end %>
                <% end %>
              </ul>
              <form class="form-inline">
                <!-- <div class="md-form my-0">
                  <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                </div> -->
                <!-- <li class="nav-item"> -->
                  <a class="nav-link text-align-right blue" style="color:white;" <%= link_to "Sign Out", logout_path, method: :delete %></a>
                <!-- </li> -->
              </form>
            </div>
          </div>
        </nav>
        <!-- Navbar -->

        <!-- Full Page Intro -->
        <div class="view" style="background-image: url('https://www.trumphotels.com/uploads/17288/16/cloudinary/trump-hotels-cloudinary/image/upload/x_78,y_194,w_1389,h_1800,c_crop/c_fill,w_1666,ar_119:73/v1523290077/oj25tuldgxunuxgsodmr.jpg'); background-repeat: no-repeat; background-size: cover; background-position: center center; opacity: 0.90;">
          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-light align-items-center">
            <!-- Content -->
            <div class="container">
              <!--Grid row-->
              <div class="row">
                <!--Grid column-->
                <div class="col-md-12 mb-4 white-text text-center">
                  <br>
                  <h1 class="h1-reponsive white-text text-uppercase font-weight-bold mb-0 pt-md-5 pt-5 wow fadeInDown" data-wow-delay="0.3s"><strong><%= @lister.name.titleize %>'s Listing Profile</strong></h1><br>
                  <!-- <hr class="hr-light my-4 wow fadeInDown" data-wow-delay="0.4s"> -->
                </div>
                <br>
                <div class="card" style="border-radius:20px; width: 30rem; background-color:transparent; margin-left:32%; margin-top:0; background-color: rgba(255, 255, 255, 0.75);">
                  <div class="card-body col text-center">
                    <% if @lister.img_url %>
                      <div class="img-thumbnail"> <%= image_tag @lister.img_url %></div>
                    <% else %>
                      <img class="img-thumbnail" src="/images/<%= @random_image %>" style="max-height:40%; max-width:40%;">
                    <% end %>

                    <h4>Properties:</h4>
                      <% if !@lister.listings.empty? %>
                        <% @lister.listings.each do |listing| %>
                          <li style="color:white;"><%= link_to listing.location, listing_path(listing) %></li><br>
                        <% end %>
                      <% else %>
                        <li>You currently have zero listings</li>
                      <% end %>
                  </div>
                </div>
              </div>
              <!--Grid row-->
            </div>
            <!-- Content -->
          </div>
          <!-- Mask & flexbox options-->
        </div>
        <!-- Full Page Intro -->
      </header>
      <!-- Main navigation -->
      <!--Main Layout-->
      <main>


      </main>
      <!--Main Layout-->


      <footer class="text-center">
          <h4>BestBooking!</h4>
          <p>All Rights Reserved &trade;</p>
      </footer>

    </body>
</html>

app/views/listings/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<%= stylesheet_link_tag "listings" %>
	<title>New Listing</title>
</head>
<body>
    <% if flash[:error] %>
      <% flash[:error].each do |error| %>
        <li style="color:red"><%= error %></li>
      <% end %>
    <% end %>
      <header>
        <!--Navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top scrolling-navbar" style="position:absolute">
          <div class="container">
            <a class="logo navbar-brand" href="<%= welcome_1_path %>"><img src="/images/BestBookingTransparent.jpg" style="max-height: 50px;"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-7" aria-controls="navbarSupportedContent-7" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent-7">
              <ul class="navbar-nav mr-auto">
                <% if !session[:user_id] %>
                <li class="nav-item active">
                  <a class="nav-link-1" <%= link_to "Listings", listings_path %></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link-1" <%= link_to "Create Profile", new_user_path, method: :get %></a>
                </li>
                <% else %>
                <li class="nav-item">
                  <a class="nav-link-1" <%= link_to "View Profile", user_path(session[:user_id]), method: :get %></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link-1" <%= link_to "Edit Listing", edit_listing_path(@listing), method: :get %></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link-1" <%= link_to "All Listings", listings_path %></a>
                </li>
                <% end %>
              </ul>
              <form class="form-inline">
                <!-- <div class="md-form my-0">
                  <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                </div> -->
                <!-- <li class="nav-item"> -->
                <% if @listing.user.id == session[:user_id] %>
                  <a class="nav-link text-align-right blue" <%= link_to "Delete", listing_path(@listing), method: :delete, data: {confirm: "Are you sure you want to delete this Listing and all of its Bookings?"} %></a>
                <% end %>
                  <a class="nav-link text-align-right blue" <%= link_to "Sign Out", logout_path, method: :delete %></a>
                <!-- </li> -->
              </form>
            </div>
          </div>
        </nav>
        <!-- Navbar -->

        <!-- Full Page Intro -->
        <div class="view" style="background-image: url('https://thenypost.files.wordpress.com/2018/10/celeb-111.jpg?quality=90&strip=all&w=978&h=652&crop=1'); background-repeat: no-repeat; background-size: cover; background-position: center center; opacity: 0.90;">
          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-light align-items-center">
            <!-- Content -->
            <div class="container">
              <!--Grid row-->
              <div class="row">
                <!--Grid column-->
                <div class="col-md-12 mb-4 white-text text-center">
                  <br>
                  <br>
                  <h1 class="h1-reponsive white-text text-uppercase font-weight-bold mb-0 pt-md-5 pt-5 wow fadeInDown" data-wow-delay="0.3s"><strong><%= @listing.location %></strong></h1><br>
                  <!-- <hr class="hr-light my-4 wow fadeInDown" data-wow-delay="0.4s"> -->
                </div>
                <br>
                <br>
                <div class="container text-center">
                  <h3>Listing Owner: <br><%= link_to @listing.user.name.titleize, lister_show_path(@listing.user) %></h3>
                </div>
                <div class="list-img">
                  <% if @listing.img_url %>
                    <div id="list-img" style="margin-left:425px; height: auto; width: auto; max-width: 300px; max-height: 300px;"><%= image_tag @listing.img_url %></div>
                  <% else %>
                    <img src="/images/<%= @random_image %>" style="max-height:40%; max-width:40%; display: block; margin-left: auto; margin-right: auto; width: 50%;">
                  <% end %><br>
                </div>
              </div>
              <!--Grid row-->
            </div>
            <!-- Content -->
          </div>
          <!-- Mask & flexbox options-->
        </div>
        <!-- Full Page Intro -->
      </header>
      <!-- Main navigation -->
      <!--Main Layout-->
      <main>
        <br><div class="container" style="background-color: rgba(0, 0, 0, 0.3); border-radius: 8px;">
          <%= month_calendar(attribute: :start_date, end_attribute: :end_date, events: @listing.bookings) do |date, bookings| %>
            <%=date.day%>
            <% if @listing.user.id != session[:user_id] %>
              <% if session[:user_id] && date >= Date.today %>
                <div id="avail" style = text-align:center;><%= button_to "Available", create_booking_path(date, @listing.id), method: :get %></div>
              <% end %>
            <% end %>
              <% bookings.each do |booking| %>
                <% if booking.user.id == session[:user_id] %>
                  <%= "Booked by:" %><br>
                  <div style = text-align:center;><%= button_to "You", booking_path(booking), method: :get %></div>
                <% else %>
                  <%= "Booked by:" %><br>
                  <div style = text-align:center;><%= "#{booking.user.name.titleize}" %></div>
                <% end %>
              <% end %>
          <% end %>
        </div>

      </main>
      <!--Main Layout-->

      <footer class="text-center">
          <h4>BestBooking!</h4>
          <p>All Rights Reserved &trade;</p>
      </footer>

    </body>
</html>