config/routes.rb
Rails.application.routes.draw do

  resources :users, except: :index
  resources :listings, only: [:index, :new, :create, :update, :show, :destroy]
  resources :bookings, only: [:index, :new, :create, :update, :show, :destroy]

  get '/', to: 'application#welcome_1', as: 'welcome_1'

  get '/login', to: 'sessions#new', as: 'new_session'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get '/about', to: "application#about", as: 'about'

  get '/lister_show/:id', to: 'listings#lister_show', as: 'lister_show'

  get '/users/:id/new_listing', to: "listings#new", as: "create_listing"
  get '/users/:id/lister_listing', to: "listings#lister_listing", as: "lister_listing"
  get '/users/:id/edit_listing', to: "listings#edit", as: "edit_listing"

  get '/users/:start_date/:id/new_booking', to: "bookings#new", as: "create_booking"
  get '/users/:id/edit_booking', to: "bookings#edit", as: "edit_booking"

end

app/models/booking.rb
class Booking < ApplicationRecord

  attr_accessor :temp_start, :temp_end


  belongs_to :listing
  belongs_to :user

  validates :start_date, :end_date, presence: true

  validate :end_date_is_after_start_date



	def to_d
		%Q(#{self.start_date.strftime("%b %-d, %Y")} -
		#{self.end_date.strftime("%b %-d, %Y")})
	end


  #######
  private
  #######

  def end_date_is_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "cannot be before the start date")
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  before_action :authorized, only: [:new, :create]

  def index
    @bookings = Booking.all
  end

  def show
    # if @booking.class == String
      if @booking.include?"Not Found"
        @user = User.find(session[:user_id])
        flash[:notice] = "#{@booking.split(" Not Found").first}. Redirected to current bookings."

        return redirect_to user_path(@user)
      end
    # end

      flash[:error] = nil
      flash[:notice] = nil
      @user = User.find(session[:user_id])
      @images  = ["1.jpeg", "2.jpeg", "3.jpeg", "4.jpeg", "5.jpeg", "6.jpeg", "8.jpeg", "9.jpeg", "10.jpeg", "11.jpeg", "12.jpeg", "13.jpeg", "14.jpeg", "15.jpeg", "16.jpeg", "17.jpeg", "19.jpeg", "21.jpeg", "22.jpeg", "23.jpeg", "24.jpeg", "25.jpeg", "26.jpeg", "27.jpg", "28.jpg", "29.jpg", "30.jpg", "31.jpg"]
      @random_no = rand(29)
      @random_image = @images[@random_no]

      render :show
  end

  def new
   @booking = Booking.new
   if Date.parse(params[:start_date]) < Date.today
     flash[:notice] = "Earliest booking date is #{Date.today.strftime("%b %-d")}"
     @booking.start_date = Date.today
   else
     @booking.start_date = params[:start_date]
   end
   @listing = Listing.find(params[:id])
   @user = User.find(session[:user_id])
  end

  def create
   @booking = Booking.new(booking_params)
   if @booking.valid?
     books = @booking.listing.bookings.map{|k,v|{k.id=>k.start_date..k.end_date}}
     not_rejected = books.reject{|h|h[@booking.id]}
     ranged = not_rejected.map{|h|h.values}.flatten

     temp_updated_dates = @booking.start_date..@booking.end_date
     temp_updated_dates.each do |d|
       ranged.each do |r|
         if r.cover?d
           flash[:notice] = "Listing already booked for those days"
           return redirect_to create_booking_path(@booking.start_date, @booking.listing.id)
         end
       end
     end
     @booking.save
     session[:booking_id] = @booking.id
     redirect_to booking_path(@booking)
   else
     redirect_to new_booking_path
   end
  end

  def edit
    flash[:notice] = nil
    flash[:error] = nil
  end

  def update
    @booking.update(booking_params)
    @booking.start_date = @booking.temp_start
    @booking.end_date = @booking.temp_end
    if @booking.valid?
     books = @booking.listing.bookings.map{|k,v|{k.id=>k.start_date..k.end_date}}
     not_rejected = books.reject{|h|h[@booking.id]}
     ranged = not_rejected.map{|h|h.values}.flatten

     temp_updated_dates = @booking.start_date..@booking.end_date
     temp_updated_dates.each do |d|
       ranged.each do |r|
         if r.cover?d
           flash[:notice] = "Listing already booked for those days"
           return render :edit
         end
       end
     end
     @booking.save
     redirect_to booking_path(@booking)
    else
      flash[:error] = @booking.errors.full_messages
      render :edit
    end
  end

  def destroy
    @booking.destroy
    redirect_to user_path(@booking.user)
  end

  private

  def set_booking
    begin
      @booking = Booking.find(params[:id])
    rescue ActiveRecord::RecordNotFound => e
      @booking = "#{e} Not Found"
    end
  end

  def booking_params
    params.require(:booking).permit(:listing_id, :user_id, :start_date, :end_date, :temp_start, :temp_end)
  end

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/edit.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
  	<meta charset="UTF-8">
  	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
  	<meta name="viewport" content="width=device-width, initial-scale=1">
  	<title>Edit Booking</title>
  </head>
  <body>
    <header>
      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark fixed-top scrolling-navbar" style="position:absolute">
        <div class="container">
          <a class="logo navbar-brand" href="<%= welcome_1_path %>"><img src="/images/BestBookingTransparent.jpg" style="max-height: 50px;"></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-7" aria-controls="navbarSupportedContent-7" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent-7">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="nav-link-1" <%= link_to "View Profile", user_path(session[:user_id]), method: :get %></a>
              </li>
              <li class="nav-item active">
                <a class="nav-link-1" <%= link_to "All Listings", listings_path %></a>
              </li>
            </ul>
            <form class="form-inline">
              <% if @booking.user == session[:user_id] %>
                <a class="nav-link text-align-right blue" <%= link_to "Delete Booking", booking_path(@booking), method: :delete, data: {confirm: "Are you sure you want to delete your booking?"} %></a>
              <% end %>
              <a class="nav-link text-align-right blue" <%= link_to "Sign Out", logout_path, method: :delete %></a>
            </form>
          </div>
        </div>
      </nav>
      <!-- Navbar -->

      <!-- Full Page Intro -->
      <div class="view" style="background-image: url('http://s3.amazonaws.com/nocnok/casa-minimalista-v1.jpg'); background-repeat: no-repeat; background-size: cover; background-position: center center; opacity: 0.90;">
        <!-- Mask & flexbox options-->
        <div class="mask rgba-black-light align-items-center">
          <!-- Content -->
          <div class="container">
            <!--Grid row-->
            <div class="row">
              <!--Grid column-->
              <div class="col-md-12 mb-4 white-text text-center">
                <br>
                <br>
                <h1 class="h1-reponsive white-text text-uppercase font-weight-bold mb-0 pt-md-5 pt-5 wow fadeInDown" data-wow-delay="0.3s"><strong>Edit Your Booking!</strong></h1><br>
                <!-- <hr class="hr-light my-4 wow fadeInDown" data-wow-delay="0.4s"> -->
              </div>
              <br>
              <br>
              <div class="card" style="width: 18rem; background-color:transparent; margin-left:37%; background-color: rgba(0, 0, 0, 0.25);">
                <div class="card-body col text-center">
                  <% @booking.temp_start = @booking.start_date %>
                   <% @booking.temp_end = @booking.end_date %>

                   <h4><%= @booking.listing.location %></h4>
                   <h6 style="color:white;">Current Booking Dates:</h6>
                   <div style="font-size:12px;"><%= @booking.to_d %></div><br>

                     <div class="container text-center">
                       <%= form_for @booking do |f| %>

                           <% if flash[:error] %>
                             <% flash[:error].each do |error| %>
                               <li style="color:red"><%= error %></li>
                             <% end %>
                           <% end %>

                           <div style="color:red"><%= flash[:notice] %></div>

                        <%= f.label :start_date %>
                        <%= f.date_field :temp_start, min: Date.today %><br><br>

                        <%= f.label :end_date %>
                        <%= f.date_field :temp_end, min: Date.today%><br><br>
                        <%= f.submit class: "btn btn-dark"%>
                      <% end %>
                </div>
              </div>
            </div>
            <!--Grid row-->
          </div>
          <!-- Content -->
        </div>
        <!-- Mask & flexbox options-->
      </div>
      <!-- Full Page Intro -->
    </header>
    <!-- Main navigation -->
    <!--Main Layout-->
    <main>

      <br><div class="container" style="background-color: rgba(0, 0, 0, 0.3); border-radius: 8px;">
       <%= month_calendar(attribute: :start_date, end_attribute: :end_date, events: @booking.listing.bookings) do |date, bookings| %>

         <%=date.day%>
         <% if session[:user_id] && date >= Date.today %>
          <div id="avail"><%="Available"%></div>
         <% end %>
         <% bookings.each do |booking| %>
          <% if booking.user.id == session[:user_id] %>
           <%= "Booked by:" %><br>
           <div style = text-align:center;><%= button_to "You", booking_path(booking), method: :get %></div>

           <% else %>
           <%= "Booked by:"%>
           <div style = text-align:center;><%= "#{booking.user.name}" %></div>
          <% end %>
         <% end %>
       <% end %>
      </div>

    </main>
    <!--Main Layout-->


    <footer class="text-center">
        <h4>BestBooking!</h4>
        <p>All Rights Reserved &trade;</p>
    </footer>

  </body>
</html>

app/views/bookings/index.html.erb
<h1>Bookings:</h1>

<% @bookings.each do |b| %>
  <li><%= link_to b.listing.location, booking_path(b) %></li>
<% end %>

app/views/bookings/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<%= stylesheet_link_tag "listings" %>
	<title>New Booking</title>
</head>
<body>
      <header>
        <!--Navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top scrolling-navbar" style="position:absolute">
          <div class="container">
            <a class="logo navbar-brand" href="<%= welcome_1_path %>"><img src="/images/BestBookingTransparent.jpg" style="max-height: 50px;"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-7" aria-controls="navbarSupportedContent-7" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent-7">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <a style="color:rgb(139, 123, 121)" class="nav-link-1" <%= link_to "View Profile", user_path(session[:user_id]), method: :get %></a>
                </li>
                <li class="nav-item active">
                  <a style="color:rgb(139, 123, 121)" class="nav-link-1" <%= link_to "All Listings", listings_path %></a>
                </li>
              </ul>
              <form class="form-inline">
                <!-- <div class="md-form my-0">
                  <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                </div> -->
                <!-- <li class="nav-item"> -->
                  <a style="color:rgb(139, 123, 121)" class="nav-link text-align-right blue" <%= link_to "Sign Out", logout_path, method: :delete %></a>
                <!-- </li> -->
              </form>
            </div>
          </div>
        </nav>
        <!-- Navbar -->

        <!-- Full Page Intro -->
        <div class="view" style="background-image: url('http://s3.amazonaws.com/nocnok/casa-minimalista-v1.jpg'); background-repeat: no-repeat; background-size: cover; background-position: center center; opacity: 0.90;">
          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-light align-items-center">
            <!-- Content -->
            <div class="container">
              <!--Grid row-->
              <div class="row">
                <!--Grid column-->
                <div class="col-md-12 mb-4 white-text text-center">
                  <br>
                  <br>
                  <h1 style="color:rgb(71, 83, 51)" class="h1-reponsive white-text text-uppercase font-weight-bold mb-0 pt-md-5 pt-5 wow fadeInDown" data-wow-delay="0.3s"><strong>Book a Listing!</strong></h1><br>
                  <!-- <hr class="hr-light my-4 wow fadeInDown" data-wow-delay="0.4s"> -->
                </div>
                <br>
                <br>
                <div class="card" style="border-radius:20px;width: 18rem; background-color:transparent; margin-left:37%; background-color: rgba(255, 255, 255, 0.25);">
                  <div class="card-body col text-center">
                    <h4>Choose Your</h4>
                    <h4>End Date</h4>
                    <%= form_for @booking do |f| %>
                      <%= f.hidden_field :user_id, value: @user.id %>
                      <%= f.hidden_field :listing_id, value: @listing.id %>
                      <%= f.hidden_field :start_date, value: @booking.start_date %>

                          <% if flash[:error] %>
                            <% flash[:error].each do |error| %>
                              <li style="color:red"><%= error %></li>
                            <% end %>
                          <% end %>

                              <div style="color:red"><%= flash[:notice] %></div>

                      <%= f.label :start_date %>:
                      <div><%= @booking.start_date.strftime("%b %-d, %Y") %></div><br>

                      <%= f.label :end_date %>:<br>
                      <%= f.date_field :end_date, min: @booking.start_date %><br><br>

                      <%= f.submit class: "btn btn-dark"%>
                    <% end %>
                    <%= button_to "Back", listing_path(@listing), method: :get%>
                  </div>
                </div>
              </div>
              <!--Grid row-->
            </div>
            <!-- Content -->
          </div>
          <!-- Mask & flexbox options-->
        </div>
        <!-- Full Page Intro -->
      </header>
      <!-- Main navigation -->
      <!--Main Layout-->
      <main>
        <!-- <div class="container">
          <!--Grid row-->
          <!-- <div class="row py-5"> -->
            <!--Grid column-->
            <!-- <div class="col-md-12 text-center"> -->
              <!-- <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
              <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
              <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p> -->
            <!-- </div> -->
            <!--Grid column-->
          <!-- </div> -->
          <!--Grid row-->
        <!-- </div> -->
      </main>
      <!--Main Layout-->


      <footer class="text-center">
          <h4>BestBooking!</h4>
          <p>All Rights Reserved &trade;</p>
      </footer>

    </body>
</html>

app/views/bookings/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<%= stylesheet_link_tag "listings" %>
	<title>New Booking</title>
</head>
<body>
    <% if flash[:error] %>
      <% flash[:error].each do |error| %>
        <li style="color:red"><%= error %></li>
      <% end %>
    <% end %>
    <%= flash[:notice] %>
      <header>
        <!--Navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top scrolling-navbar" style="position:absolute">
          <div class="container">
            <a class="logo navbar-brand" href="<%= welcome_1_path %>"><img src="/images/BestBookingTransparent.jpg" style="max-height: 50px;"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-7" aria-controls="navbarSupportedContent-7" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent-7">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <a class="nav-link-1" <%= link_to "View Profile", user_path(session[:user_id]), method: :get %></a>
                </li>
                <li class="nav-item active">
                  <a class="nav-link-1" <%= link_to "All Listings", listings_path %></a>
                </li>
                <li class="nav-item active">
                  <a class="nav-link-1" <%= link_to "Edit Booking", edit_booking_path %></a>
                </li>
              </ul>
              <form class="form-inline">
                <!-- <div class="md-form my-0">
                  <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                </div> -->
                <!-- <li class="nav-item"> -->
                <a class="nav-link-1 blue" <%= link_to "Delete Booking", booking_path(@booking), method: :delete, data: {confirm: 'Delete Booking?'} %></a>
                <a class="nav-link text-align-right blue" <%= link_to "Sign Out", logout_path, method: :delete %></a>
                <!-- </li> -->
              </form>
            </div>
          </div>
        </nav>
        <!-- Navbar -->

        <!-- Full Page Intro -->
        <div class="view" style="background-image: url('https://images.ctfassets.net/z7ety0aygnfq/2RSp1hCKnCCcW0eKgc4wcq/50436892cb4de943d5f9f7a4e0b84247/Suhde169_StudioKoti_nostokuva.jpg'); background-repeat: no-repeat; background-size: cover; background-position: center center; opacity: 0.90;">
          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-light align-items-center">
            <!-- Content -->
            <div class="container">
              <!--Grid row-->
              <div class="row">
                <!--Grid column-->
                <div class="col-md-12 mb-4 white-text text-center">
                  <br>
                  <br>
                  <h1 class="h1-reponsive white-text text-uppercase font-weight-bold mb-0 pt-md-5 pt-5 wow fadeInDown" data-wow-delay="0.3s"><strong>Here is your Booking!</strong></h1><br>
                  <!-- <hr class="hr-light my-4 wow fadeInDown" data-wow-delay="0.4s"> -->
                </div>
                <br>
                <br>
                <h4 class="lead" style="margin-left:40%;">Upcoming Booking details:</h4>
                <div class="card col-sm-4" style="border-radius:20px; width: 18rem; background-color:transparent; margin-left:35%; background-color: rgba(255, 255, 255, 0.75);">
                  <div class="card-body col text-center">
                    <h6>Address:</h6>
                    <%= link_to @booking.listing.location, listing_path(@booking.listing) %><br><br>
                    <h6>Dates:</h6>
                    <div><%= @booking.to_d %></div><br>

                    <%# if @booking.listing.img_url %>
                      <!-- <div class="img-thumbnail"><%# image_tag @booking.listing.img_url %></div> -->
                    <%# else %>
                      <img class="img-thumbnail" src="/images/<%= @random_image %>" style="max-height:40%; max-width:40%; display: block; margin-left: auto; margin-right: auto; width: 50%;">
                    <%# end %>
                  </div>
                </div>
              </div>
              <!--Grid row-->
            </div>
            <!-- Content -->
          </div>
          <!-- Mask & flexbox options-->
        </div>
        <!-- Full Page Intro -->
      </header>
      <!-- Main navigation -->
      <!--Main Layout-->
      <main>
        <!-- <div class="container">
          <!--Grid row-->
          <!-- <div class="row py-5"> -->
            <!--Grid column-->
            <!-- <div class="col-md-12 text-center"> -->
              <!-- <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
              <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
              <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p> -->
            <!-- </div> -->
            <!--Grid column-->
          <!-- </div> -->
          <!--Grid row-->
        <!-- </div> -->
      </main>
      <!--Main Layout-->


      <footer class="text-center">
          <h4>BestBooking!</h4>
          <p>All Rights Reserved &trade;</p>
      </footer>

    </body>
</html>