config/routes.rb
Rails.application.routes.draw do

  resources :users, except: :index
  resources :listings, only: [:index, :new, :create, :update, :show, :destroy]
  resources :bookings, only: [:index, :new, :create, :update, :show, :destroy]

  get '/', to: 'application#welcome_1', as: 'welcome_1'

  get '/login', to: 'sessions#new', as: 'new_session'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get '/about', to: "application#about", as: 'about'

  get '/lister_show/:id', to: 'listings#lister_show', as: 'lister_show'

  get '/users/:id/new_listing', to: "listings#new", as: "create_listing"
  get '/users/:id/lister_listing', to: "listings#lister_listing", as: "lister_listing"
  get '/users/:id/edit_listing', to: "listings#edit", as: "edit_listing"

  get '/users/:start_date/:id/new_booking', to: "bookings#new", as: "create_booking"
  get '/users/:id/edit_booking', to: "bookings#edit", as: "edit_booking"

end

app/models/user.rb
class User < ApplicationRecord
  has_many :listings
  has_many :bookings, through: :listings
  has_many :bookings
  has_secure_password

  validates :name, :email, :password_digest, presence: true
  validates :email, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show
    @images  = ["ppl-1.jpeg", "ppl-2.jpeg", "ppl-3.jpeg", "ppl-4.jpeg", "ppl-5.jpeg", "ppl-6.jpeg", "ppl-7.jpeg", "ppl-8.jpeg", "ppl-9.jpeg", "ppl-10.jpeg", "ppl-11.jpeg", "ppl-13.jpeg", "ppl-14.jpeg", "ppl-15.jpeg", "ppl-16.jpeg", "ppl-17.jpeg", "ppl-18.jpeg", "ppl-19.jpeg", "ppl-20.jpeg", "ppl-21.jpeg", "ppl-22.jpeg", "ppl-24.jpeg", "ppl-25.jpeg", "ppl-26.jpeg"]
    @random_no = rand(24)
    @random_image = @images[@random_no]
  end

  def new
    @user = User.new
    flash[:error] = nil
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:error] = @user.errors.full_messages
      render :new
    end
  end

  def edit
    flash[:error] = nil
  end

  def update
    @user.update(user_params)
    if @user.valid?
      redirect_to user_path(@user)
    else
      flash[:error] = @user.errors.full_messages
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to welcome_1_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :img_url)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Edit Profile</title>
</head>
<body>
    <% if flash[:error] %>
      <% flash[:error].each do |error| %>
        <li style="color:red"><%= error %></li>
      <% end %>
    <% end %>
      <header>
        <!--Navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top scrolling-navbar" style="position:absolute">
          <div class="container">
            <a class="logo navbar-brand" href="<%= welcome_1_path %>"><img src="/images/BestBookingTransparent.jpg" style="max-height: 50px;"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-7" aria-controls="navbarSupportedContent-7" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent-7">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" <%= link_to "All Listings", listings_path %></a>
                </li>
                <li class="nav-item active">
                  <a class="nav-link" <%= link_to "Create a Listing", create_listing_path %></a>
                </li>
                <li class="nav-item active">
                  <a class="nav-link" <%= link_to "View Profile", user_path(session[:user_id]), method: :get %></a>
                </li>
              </ul>
              <form class="form-inline">
                <!-- <div class="md-form my-0">
                  <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                </div> -->
                <!-- <li class="nav-item"> -->
                  <a class="nav-link text-align-right blue" <%= link_to "Sign Out", logout_path, method: :delete %></a>
                <!-- </li> -->
              </form>
            </div>
          </div>
        </nav>
        <!-- Navbar -->

        <!-- Full Page Intro -->
        <div class="view" style="background-image: url('https://img1.coastalliving.timeinc.net/sites/default/files/styles/4_3_horizontal_inbody_900x506/public/image/2016/06/main/white-bedroom-ocean-view-bed16_foul.jpg?itok=2BfoCEjV'); background-repeat: no-repeat; background-size: cover; background-position: center center; opacity: 0.90;">
          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-light align-items-center">
            <!-- Content -->
            <div class="container">
              <!--Grid row-->
              <div class="row">
                <!--Grid column-->
                <div class="col-md-12 mb-4 white-text text-center">
                  <br>
                  <br>
                  <h1 class="h1-reponsive white-text text-uppercase font-weight-bold mb-0 pt-md-5 pt-5 wow fadeInDown" data-wow-delay="0.3s"><strong>Edit Your Profile</strong></h1><br>
                  <!-- <hr class="hr-light my-4 wow fadeInDown" data-wow-delay="0.4s"> -->
                </div>
                <br>
                <br>
                <div class="card" style="width: 18rem; background-color:transparent; margin-left:38%; background-color: rgba(255, 255, 255, 0.5);">
                  <div class="card-body col text-center" style="color:rgb(30, 67, 139);">
                    <%= form_for @user do |f| %>
                		<%= f.label :name %><br>
                		<%= f.text_field :name %><br>

                		<%= f.label :email %><br>
                		<%= f.text_field :email %><br>

                		<%= f.label :password %><br>
                		<%= f.text_field :password %><br>

                		<%= f.label :password_confirmation, "Confirm Password" %><br>
                		<%= f.text_field :password_confirmation %><br>

                		<%= f.label :img_url %><br>
                		<%= f.text_field :img_url %><br><br>

                		<%= f.submit class: "btn btn-dark"%>
                		<% end %>
                  </div>
                </div>
              </div>
              <!--Grid row-->
            </div>
            <!-- Content -->
          </div>
          <!-- Mask & flexbox options-->
        </div>
        <!-- Full Page Intro -->
      </header>
      <!-- Main navigation -->
      <!--Main Layout-->
      <main>
        <!-- <div class="container">
          <!--Grid row-->
          <!-- <div class="row py-5"> -->
            <!--Grid column-->
            <!-- <div class="col-md-12 text-center"> -->
              <!-- <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
              <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
              <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p> -->
            <!-- </div> -->
            <!--Grid column-->
          <!-- </div> -->
          <!--Grid row-->
        <!-- </div> -->
      </main>
      <!--Main Layout-->


      <footer class="text-center">
          <h4>BestBooking!</h4>
          <p>All Rights Reserved &trade;</p>
      </footer>

    </body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>New Listing</title>
</head>
<body>
      <header>
        <!--Navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top scrolling-navbar" style="position:absolute">
          <div class="container">
            <a class="logo navbar-brand" href="<%= welcome_1_path %>"><img src="/images/BestBookingTransparent.jpg" style="max-height: 50px;"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-7" aria-controls="navbarSupportedContent-7" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent-7">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" <%= link_to "All Listings", listings_path %></a>
                </li>
              </ul>
              <form class="form-inline">
                <!-- <div class="md-form my-0">
                  <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                </div> -->
                <!-- <li class="nav-item"> -->
                  <a class="nav-link text-align-right blue" <%= link_to "Sign Out", logout_path, method: :delete %></a>
                <!-- </li> -->
              </form>
            </div>
          </div>
        </nav>
        <!-- Navbar -->

        <!-- Full Page Intro -->
        <div class="view" style="background-image: url('https://img1.coastalliving.timeinc.net/sites/default/files/styles/4_3_horizontal_inbody_900x506/public/image/2016/06/main/white-bedroom-ocean-view-bed16_foul.jpg?itok=2BfoCEjV'); background-repeat: no-repeat; background-size: cover; background-position: center center; opacity: 0.90;">
          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-light align-items-center">
            <!-- Content -->
            <div class="container">
              <!--Grid row-->
              <div class="row">
                <!--Grid column-->
                <div class="col-md-12 mb-4 white-text text-center">
                  <br>
                  <br>
                  <h1 class="h1-reponsive white-text text-uppercase font-weight-bold mb-0 pt-md-5 pt-5 wow fadeInDown" data-wow-delay="0.3s"><strong>Create a New Account</strong></h1><br>
                  <!-- <hr class="hr-light my-4 wow fadeInDown" data-wow-delay="0.4s"> -->
                </div>
                <br>
                <br>
                <div class="card" style="border-radius:20px; width: 18rem; background-color:transparent; margin-left:38%; background-color: rgba(255, 255, 255, 0.5)">
                  <div class="card-body col text-center" style="color:rgb(63, 156, 197)">


                        <% if flash[:error] %>
                          <% flash[:error].each do |error| %>
                            <li style="color:red; font-size:12px;"><%= error %></li>
                          <% end %>
                        <% end %>

                    <%= form_for @user do |f| %>
                    <%= f.label :name %><br>
                    <%= f.text_field :name %><br>

                    <%= f.label :email %><br>
                    <%= f.email_field :email %><br>

                    <%= f.label :password %><br>
                    <%= f.text_field :password %><br>

                    <%= f.label :password_confirmation, "Confirm Password" %><br>
                    <%= f.text_field :password_confirmation %><br>

                    <%= f.label :img_url %><br>
                    <%= f.text_field :img_url %><br><br>

                    <%= f.submit class: "btn btn-dark"%>
                    <% end %>
                  </div>
                </div>
              </div>
              <!--Grid row-->
            </div>
            <!-- Content -->
          </div>
          <!-- Mask & flexbox options-->
        </div>
        <!-- Full Page Intro -->
      </header>
      <!-- Main navigation -->
      <!--Main Layout-->
      <main>
        <!-- <div class="container">
          <!--Grid row-->
          <!-- <div class="row py-5"> -->
            <!--Grid column-->
            <!-- <div class="col-md-12 text-center"> -->
              <!-- <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
              <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
              <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p> -->
            <!-- </div> -->
            <!--Grid column-->
          <!-- </div> -->
          <!--Grid row-->
        <!-- </div> -->
      </main>
      <!--Main Layout-->


      <footer class="text-center">
          <h4>BestBooking!</h4>
          <p>All Rights Reserved &trade;</p>
      </footer>

    </body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<%= stylesheet_link_tag "listings" %>
	<title>New Listing</title>
</head>
<body class="bgcolor-fill">

      <header>
        <!--Navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top scrolling-navbar" style="position:absolute">
          <div class="container">
            <a class="logo navbar-brand" href="<%= welcome_1_path %>"><img src="/images/BestBookingTransparent.jpg" style="max-height: 50px;"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-7" aria-controls="navbarSupportedContent-7" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent-7">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <a style="color:rgb(48, 128, 124)" class="nav-link-1" <%= link_to "Edit Your Profile", edit_user_path(@user) %></a>
                </li>
                <li class="nav-item">
                  <a style="color:rgb(48, 128, 124)" class="nav-link-1" <%= link_to "All Listings", listings_path %></a>
                </li>
                <li class="nav-item">
                  <a style="color:rgb(48, 128, 124)" class="nav-link-1" <%= link_to "Create a Listing", create_listing_path %></a>
                </li>
              </ul>
              <form class="form-inline">
                <!-- <div class="md-form my-0">
                  <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                </div> -->
                <!-- <li class="nav-item"> -->
                  <a style="color:rgb(48, 128, 124)" class="nav-link text-align-right blue" <%= link_to "Sign Out", logout_path, method: :delete %></a>
                <!-- </li> -->
              </form>
            </div>
          </div>
        </nav>
        <!-- Navbar -->

      <!-- Stretch background container -->
      <div>
        <!-- Full Page Intro -->
        <div class="view" style="background-image: url('https://cdn-image.travelandleisure.com/sites/default/files/styles/1600x1000/public/1525474227/049-il-san-pietro-di-positano-TOP100HOTELS0518.jpg?itok=zOnhoTGE'); background-repeat: no-repeat; background-size: cover; background-position: center center; opacity: 0.90;">
          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-light align-items-center">
            <!-- Content -->
            <div class="container">
              <!--Grid row-->
              <div class="row">
                <!--Grid column-->
                <div class="col-md-12 mb-4 white-text text-center">
                  <br>
                  <br>
                  <br>
                  <br>
                  <br>
                  <br>
                  <h1 class="h1-reponsive white-text text-uppercase font-weight-bold mb-0 pt-md-5 pt-5 wow fadeInDown" style="color:black;" data-wow-delay="0.3s">Hi, <%= @user.name.titleize %>!</h1><br>
                  <!-- <hr class="hr-light my-4 wow fadeInDown" data-wow-delay="0.4s"> -->
                  <div class="container" style="width:55%">
                    <% if flash[:error] %>
                      <% flash[:error].each do |error| %>
                        <li style="color:red"><%= error %></li>
                      <% end %>
                    <% end %>

                    <% if flash[:notice] %>
                      <li style="color:red; background-color: rgba(238, 232, 224, 0.65);"><%= flash[:notice] %></li>
                    <% end %>
                  </div>
                </div>
                <br>

                <br><div class="container" style="margin-left:12%; border-radius:20px;">
                  <div class="row">

                    <div class="card" style="border-radius:20px; width: 18rem; background-color:transparent; background-color: rgba(238, 232, 224, 0.65);">
                      <div class="card-body col text-center" style="color:rgb(40, 127, 130)">
                        <ul>
                          <%# if @user.img_url %>
                            <!-- <div class="user-img"><%# image_tag @user.img_url %></div> -->
                          <%# else %>
                           <img src="/images/<%= @random_image %>" style="display: block; margin-left: auto; margin-right: auto; width: 60%;">
                          <%# end %>
                        </ul><br>
                      </div>
                    </div>

                    <!-- <span class="border border-primary"></span> -->

                    <div class="card" style="border-radius:20px; width: 18rem; background-color:transparent; background-color: rgba(238, 232,	224, 0.75);">
                      <div class="card-body col text-center" style="color:rgb(40, 127, 130)">
                      <h2 class="text-center"">Your Upcoming Bookings:</h2>
                        <% if @user.bookings.empty?%>
                         <!-- || @user.bookings = [] -->
                        	 <li>You Currently Have No Bookings.</li>
                        	<% else %>
                          <ul>
                        	  <% @user.bookings.each do |booking| %>
                              <% if !booking.listing.nil? %>
                          		<li><%= link_to booking.listing.location, booking_path(booking) %><br>
                          		   <strong>Dates: </strong><%= booking.to_d %></li><br>
                              <% end %>
                            <% end %>
                        	</ul>
                      	<% end %>
                      </div>
                    </div>

                    <!-- <span class="border border-primary"></span> -->

                    <div class="card" style="border-radius:20px; width: 18rem; background-color:transparent; background-color: rgba(238, 232,	224, 0.75);">
                      <div class="card-body col text-center" style="color:rgb(40, 127, 130)">
                      <h2>Your Listings:</h2>
                    	  <% if @user.listings.empty?%>
                    	    <li>You Currently Have No Listings.</li>
                    	  <% else %>
                    	   <ul>
                    	     <% @user.listings.each do |listing| %>
                    	       <li><%= link_to listing.location, listing_path(listing) %></li><br>
                    	     <% end %>
                    	   </ul>
                      	<% end %>
                      </div>

                    </div>

                  </div>

                </div>
              </div>
              <!--Grid row-->
            </div>
            <div style="height:90px;"></div>

            <!-- Content -->
          </div>
          <!-- Mask & flexbox options-->

        </div>
        <!-- Full Page Intro -->

      </div>
          <footer class="text-center" style="position: relative;">
            <h4>BestBooking!</h4>
            <p>All Rights Reserved &trade;</p>
          </footer>

      <!-- Stretch background container -->
      </header>

      <!-- Main navigation -->
      <!--Main Layout-->
      <main>

      </main>
      <!--Main Layout-->



    </body>

</html>