config/routes.rb
Rails.application.routes.draw do

  resources :users, except: :index
  resources :listings, only: [:index, :new, :create, :update, :show, :destroy]
  resources :bookings, only: [:index, :new, :create, :update, :show, :destroy]

  get '/', to: 'application#welcome_1', as: 'welcome_1'

  get '/login', to: 'sessions#new', as: 'new_session'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get '/about', to: "application#about", as: 'about'

  get '/lister_show/:id', to: 'listings#lister_show', as: 'lister_show'

  get '/users/:id/new_listing', to: "listings#new", as: "create_listing"
  get '/users/:id/lister_listing', to: "listings#lister_listing", as: "lister_listing"
  get '/users/:id/edit_listing', to: "listings#edit", as: "edit_listing"

  get '/users/:start_date/:id/new_booking', to: "bookings#new", as: "create_booking"
  get '/users/:id/edit_booking', to: "bookings#edit", as: "edit_booking"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	def welcome_1
	end

	def current_user
		if session[:user_id]
			@current_user = User.find(session[:user_id])
		end
	end

	def logged_in?
		!!current_user
	end

	def authorized
		redirect_to welcome_1_path unless logged_in?
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/about.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
      <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Welcome to Best Booking!</title>
  </head>
  <header>
    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top scrolling-navbar" style="position:absolute">
      <div class="container">
        <a class="logo navbar-brand" href="<%= welcome_1_path %>"><img src="/images/BestBookingTransparent.jpg" style="max-height: 50px;"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-7" aria-controls="navbarSupportedContent-7" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent-7">
          <ul class="navbar-nav mr-auto">
            <% if !session[:user_id] %>
            <li class="nav-item">
              <a class="nav-link blue" <%= link_to "All Listings", listings_path %></a>
            </li>
            <li class="nav-item">
              <a class="nav-link blue" <%= link_to "Log In", new_session_path, method: :get %></a>
            </li>
            <li class="nav-item">
              <a class="nav-link blue" <%= link_to "Create Profile", new_user_path, method: :get %></a>
            </li>
            <% else %>
            <li class="nav-item">
              <a class="nav-link blue" <%= link_to "View Profile", user_path(session[:user_id]), method: :get %></a>
            </li>
            <li class="nav-item">
              <a class="nav-link blue" <%= link_to "All Listings", listings_path %></a>
            </li>
            <% end %>
          </ul>
          <form class="form-inline">
            <!-- <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div> -->
            <!-- <li class="nav-item"> -->
              <a class="nav-link text-align-right blue" <%= link_to "Sign Out", logout_path, method: :delete %></a>
            <!-- </li> -->
          </form>
        </div>
      </div>
    </nav>
  <body>

    <div class="view" style="background-image: url('https://abrilcasacor.files.wordpress.com/2019/02/brut_1.jpg'); background-repeat: no-repeat; background-size: cover; background-position: center center; opacity: 0.80;">
          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-light align-items-center">
            <!-- Content -->
            <div class="container">
              <!--Grid row-->
              <div class="row">
                <!--Grid column-->
                <div class="col-md-12 mb-4 text-center">

                  <br><br><br><h1 id="welcomeheader" style="color:black;">About the Creators</h1><br><br><br>

                  <div class="flip-card">
                    <div class="flip-card-inner">
                      <div class="flip-card-front">
                        <img src="/images/cass.jpg" alt="Avatar" style="width:300px;height:300px;">
                      </div>
                      <div class="flip-card-back">
                        <h1>Cassidy Samelian</h1><br>
                        <p>Dancer & Programmer</p>
                        <p>LINKS</p>
                      </div>
                    </div>
                  </div>

                  <div class="flip-card">
                    <div class="flip-card-inner">
                      <div class="flip-card-front">
                        <img src="/images/ed.jpg" alt="Avatar" style="width:300px;height:300px;">
                      </div>
                      <div style="background-color: rgb(197, 186, 172);" class="flip-card-back">
                        <h1>Edwin Lin</h1><br>
                        <p>Chef & Humble Programmer</p>
                        <p>LINKS</p>
                      </div>
                    </div>
                  </div>

                  <div class="flip-card">
                    <div class="flip-card-inner">
                      <div class="flip-card-front">
                        <img src="/images/jon.jpg" alt="Avatar" style="width:300px;height:300px;">
                      </div>
                      <div style="background-color: rgb(92, 103, 130);" class="flip-card-back">
                        <h1>Jon Freed</h1><br>
                        <p>Playboy & Programmer</p>
                        <p>LINKS</p>
                      </div>
                    </div>
                  </div>

              </div>
              <!--Grid row-->
            </div>
            <!-- Content -->
          </div>
          <!-- Mask & flexbox options-->
        </div>

  </body>
</html>

app/views/application/welcome_1.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">

    <%= stylesheet_link_tag "application" %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
  	<meta name="viewport" content="width=device-width, initial-scale=1">
  	<!-- <%= stylesheet_link_tag "users" %> -->
    <title>Welcome to Best Booking!</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark fixed-top scrolling-navbar" style="position:absolute;">
      <div class="container">
        <a class="logo navbar-brand" href="<%= welcome_1_path %>"><img src="/images/BestBookingTransparent.jpg" style="max-height: 50px;"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-7" aria-controls="navbarSupportedContent-7" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent-7">
          <ul class="navbar-nav mr-auto">
            <% if session[:user_id].nil? %>
            <li class="nav-item">
              <a class="nav-link-1" <%= link_to "Login", new_session_path %></a>
            </li>
            <li class="nav-item">
              <a class="nav-link-1" <%= link_to "Create Account", new_user_path %></a>
            </li>
            <% else %>
            <li class="nav-item">
              <a class="nav-link-1" <%= link_to "View Profile", user_path(session[:user_id])%></a>
            </li>
            <li class="nav-item">
              <a class="nav-link-1" <%= link_to "All Listings", listings_path%></a>
            </li>
            <% end %>
            <li class="nav-item">
              <a class="nav-link-1" <%= link_to "About", about_path%></a>
            </li>
          </ul>
          <form class="form-inline">
            <!-- <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div> -->
            <!-- <li class="nav-item"> -->
            <% if session[:user_id] %>
              <a class="nav-link text-align-right blue" <%= link_to "Sign Out", logout_path, method: :delete %></a>
            <% end %>
            <!-- </li> -->
          </form>
        </div>
      </div>
    </nav><br><br><br><br>

  <!-- Grid row -->
  <!-- <div class="row"> -->

    <!-- Grid column -->
    <!-- <div class="col-md-12 d-flex justify-content-center mb-5"> -->

      <!-- <button type="button" class="btn btn-outline-black waves-effect filter" data-rel="all">All</button>
      <button type="button" class="btn btn-outline-black waves-effect filter" data-rel="1">Mountains</button>
      <button type="button" class="btn btn-outline-black waves-effect filter" data-rel="2">Sea</button> -->

    <!-- </div> -->
    <!-- Grid column -->

  <!-- </div> -->
  <!-- Grid row -->

  <!-- Grid row -->
  <div class="gallery" id="gallery" style="margin:8px;">

    <!-- Grid column -->
    <div class="mb-3 pics animation all 2">
      <img class="img-fluid" src="/images/10.jpeg" alt="Card image cap">
    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="mb-3 pics animation all 1">
      <img class="img-fluid" src="/images/32.jpeg" alt="Card image cap">
    </div>

    <div class="mb-3 pics animation all 1">
      <img class="img-fluid" src="/images/3.jpeg" alt="Card image cap">
    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="mb-3 pics animation all 2">
      <img class="img-fluid" src="/images/4.jpeg" alt="Card image cap">
    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="mb-3 pics animation all 2">
      <img class="img-fluid" src="http://www.malawi-cichlides.com/wp-content/uploads/2018/07/Apartments.jpg" alt="Card image cap">
    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="mb-3 pics animation all 1">
      <img class="img-fluid" src="/images/6.jpeg" alt="Card image cap">
    </div>

    <!-- Grid column -->
    <div class="mb-3 pics animation all 2">
      <img class="img-fluid" src="/images/13.jpeg" alt="Card image cap">
    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="mb-3 pics animation all 1">
      <img class="img-fluid" src="/images/14.jpeg" alt="Card image cap">
    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="mb-3 pics animation all 1">
      <img class="img-fluid" src="/images/1.jpeg" alt="Card image cap">
    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="mb-3 pics animation all 2">
      <img class="img-fluid" src="/images/16.jpeg" alt="Card image cap">
    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="mb-3 pics animation all 2">
      <img class="img-fluid" src="https://voltaapartments.com/wp/wp-content/uploads/2015/01/vol-50.jpg" alt="Card image cap">
    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="mb-3 pics animation all 1">
      <img class="img-fluid" src="/images/19.jpeg" alt="Card image cap">
    </div>

    <!-- Grid column -->
    <div class="mb-3 pics animation all 2">
      <img class="img-fluid" src="/images/8.jpeg" alt="Card image cap">
    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="mb-3 pics animation all 1">
      <img class="img-fluid" src="/images/27.jpg" alt="Card image cap">
    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="mb-3 pics animation all 1">
      <img class="img-fluid" src="/images/9.jpeg" alt="Card image cap">
    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="mb-3 pics animation all 2">
      <img class="img-fluid" src="/images/23.jpeg" alt="Card image cap">
    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="mb-3 pics animation all 2">
      <img class="img-fluid" src="/images/11.jpeg" alt="Card image cap">
    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="mb-3 pics animation all 2">
      <img class="img-fluid" src="/images/31.jpg" alt="Card image cap">
    </div>

    <div class="mb-3 pics animation all 1">
      <img class="img-fluid" src="/images/12.jpeg" alt="Card image cap">
    </div>
    <!-- Grid column -->

    <!-- Grid column -->

    <!-- Grid column -->
    <div class="mb-3 pics animation all 1">
      <img class="img-fluid" src="/images/30.jpg" alt="Card image cap">
    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="mb-3 pics animation all 1">
      <img class="img-fluid" src="/images/29.jpg" alt="Card image cap">
    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="mb-3 pics animation all 2">
      <img class="img-fluid" src="/images/28.jpg" alt="Card image cap">
    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="mb-3 pics animation all 2">
      <img class="img-fluid" src="/images/21.jpeg" alt="Card image cap">
    </div>
    <!-- Grid column -->

    <div class="mb-3 pics animation all 2">
      <img class="img-fluid" src="/images/28.jpg" alt="Card image cap">
    </div>

    <!-- Grid column -->
    <div class="mb-3 pics animation all 2">
      <img class="img-fluid" src="/images/26.jpeg" alt="Card image cap">
    </div>
    <!-- Grid column -->

    <div class="mb-3 pics animation all 2">
      <img class="img-fluid" src="/images/25.jpeg" alt="Card image cap">
    </div>
    <!-- Grid column -->

  </div>
  <!-- Grid row -->

  <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script> -->

  </body>
</html>